# Generated by Django 5.1.5 on 2025-05-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profile_pics/'),
        ),
    ]
